-- Shared, curated catalogue of common bar ingredients (generic, price-less).
-- Menu import matches extracted ingredients against this so a bar adopts a
-- common ingredient by entering only its own price. Distinct from the
-- barcode catalogue (specific scanned bottles, keyed by EAN-13).
CREATE TABLE pouriq_ingredient_catalogue (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  name TEXT NOT NULL,
  normalised_name TEXT NOT NULL UNIQUE,
  ingredient_type TEXT NOT NULL CHECK (ingredient_type IN
    ('spirit','liqueur','wine','beer','mixer','syrup','juice','garnish','other')),
  pricing_mode TEXT NOT NULL CHECK (pricing_mode IN ('bottle','unit')),
  default_bottle_size_ml INTEGER,
  verified INTEGER NOT NULL DEFAULT 1,
  contributor_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO pouriq_ingredient_catalogue (name, normalised_name, ingredient_type, pricing_mode, default_bottle_size_ml) VALUES
-- Spirits
('White Rum','white rum','spirit','bottle',700),
('Dark Rum','dark rum','spirit','bottle',700),
('Spiced Rum','spiced rum','spirit','bottle',700),
('Aged Rum','aged rum','spirit','bottle',700),
('Overproof Rum','overproof rum','spirit','bottle',700),
('London Dry Gin','london dry gin','spirit','bottle',700),
('Old Tom Gin','old tom gin','spirit','bottle',700),
('Vodka','vodka','spirit','bottle',700),
('Blended Scotch Whisky','blended scotch whisky','spirit','bottle',700),
('Single Malt Scotch','single malt scotch','spirit','bottle',700),
('Bourbon','bourbon','spirit','bottle',700),
('Rye Whiskey','rye whiskey','spirit','bottle',700),
('Irish Whiskey','irish whiskey','spirit','bottle',700),
('Blanco Tequila','blanco tequila','spirit','bottle',700),
('Reposado Tequila','reposado tequila','spirit','bottle',700),
('Anejo Tequila','anejo tequila','spirit','bottle',700),
('Mezcal','mezcal','spirit','bottle',700),
('Cognac','cognac','spirit','bottle',700),
('Brandy','brandy','spirit','bottle',700),
('Pisco','pisco','spirit','bottle',700),
('Cachaca','cachaca','spirit','bottle',700),
('Absinthe','absinthe','spirit','bottle',700),
-- Liqueurs
('Triple Sec','triple sec','liqueur','bottle',700),
('Cointreau','cointreau','liqueur','bottle',700),
('Campari','campari','liqueur','bottle',700),
('Aperol','aperol','liqueur','bottle',700),
('Sweet Vermouth','sweet vermouth','liqueur','bottle',750),
('Dry Vermouth','dry vermouth','liqueur','bottle',750),
('Coffee Liqueur','coffee liqueur','liqueur','bottle',700),
('Amaretto','amaretto','liqueur','bottle',700),
('Elderflower Liqueur','elderflower liqueur','liqueur','bottle',700),
('Peach Schnapps','peach schnapps','liqueur','bottle',700),
('Blue Curacao','blue curacao','liqueur','bottle',700),
('Chambord','chambord','liqueur','bottle',700),
('Maraschino Liqueur','maraschino liqueur','liqueur','bottle',700),
('Benedictine','benedictine','liqueur','bottle',700),
('Irish Cream','irish cream','liqueur','bottle',700),
('Limoncello','limoncello','liqueur','bottle',700),
('Sloe Gin','sloe gin','liqueur','bottle',700),
('Apricot Brandy','apricot brandy','liqueur','bottle',700),
('Melon Liqueur','melon liqueur','liqueur','bottle',700),
('Orange Bitters','orange bitters','liqueur','bottle',100),
('Angostura Bitters','angostura bitters','liqueur','bottle',200),
-- Wine / sparkling
('Prosecco','prosecco','wine','bottle',750),
('Champagne','champagne','wine','bottle',750),
('Red Wine','red wine','wine','bottle',750),
('White Wine','white wine','wine','bottle',750),
('Aperitif Wine','aperitif wine','wine','bottle',750),
-- Beer
('Lager','lager','beer','bottle',330),
('Alcoholic Ginger Beer','alcoholic ginger beer','beer','bottle',330),
-- Mixers
('Tonic Water','tonic water','mixer','bottle',1000),
('Soda Water','soda water','mixer','bottle',1000),
('Cola','cola','mixer','bottle',1000),
('Lemonade','lemonade','mixer','bottle',1000),
('Ginger Beer','ginger beer','mixer','bottle',1000),
('Ginger Ale','ginger ale','mixer','bottle',1000),
('Bitter Lemon','bitter lemon','mixer','bottle',1000),
-- Juices
('Lime Juice','lime juice','juice','bottle',1000),
('Lemon Juice','lemon juice','juice','bottle',1000),
('Orange Juice','orange juice','juice','bottle',1000),
('Cranberry Juice','cranberry juice','juice','bottle',1000),
('Pineapple Juice','pineapple juice','juice','bottle',1000),
('Grapefruit Juice','grapefruit juice','juice','bottle',1000),
('Apple Juice','apple juice','juice','bottle',1000),
('Tomato Juice','tomato juice','juice','bottle',1000),
('Passion Fruit Puree','passion fruit puree','juice','bottle',1000),
-- Syrups
('Sugar Syrup','sugar syrup','syrup','bottle',1000),
('Grenadine','grenadine','syrup','bottle',1000),
('Agave Syrup','agave syrup','syrup','bottle',1000),
('Honey Syrup','honey syrup','syrup','bottle',1000),
('Orgeat','orgeat','syrup','bottle',1000),
('Vanilla Syrup','vanilla syrup','syrup','bottle',1000),
('Elderflower Cordial','elderflower cordial','syrup','bottle',1000),
-- Garnishes (unit-priced)
('Lime','lime','garnish','unit',NULL),
('Lemon','lemon','garnish','unit',NULL),
('Orange','orange','garnish','unit',NULL),
('Mint Sprig','mint sprig','garnish','unit',NULL),
('Cocktail Cherry','cocktail cherry','garnish','unit',NULL),
('Olive','olive','garnish','unit',NULL),
('Cucumber','cucumber','garnish','unit',NULL),
('Egg White','egg white','garnish','unit',NULL),
('Salt Rim','salt rim','garnish','unit',NULL),
('Sugar Rim','sugar rim','garnish','unit',NULL);
